spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:13306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql
